Documentation environment model
csnazell/plant-model pull request #8
Opened 2024-11-06 17:00 UTC by csnazell

Created description of environment model and how to create a new custom model from scratch.

Addresses Issue #6 

Outstanding:

-[] Requires Circadian Model [PR](https://github.com/csnazell/plant-model/pull/5) to be merged
-[] Update Circadian Model docs to link into these

2024-11-11 14:31 UTC, ReaAntKour requested changes
This is really great! Clear instructions explaining this. I was a bit confused in just a few bits (or thought it might help to add a bit extra explanation) and include comments below.

What would the example in "creating an environment model" produce? Is it like the default but with an 8 hour photoperiod? How do you control the day duration instead?

In “#4 Create New Model - Model Data”, I would suggest adding a sentence to describe what your example will be doing to prepare the reader, before you show the code for it. e.g something like: “In this example we will set the temperature as increasing linearly from minimum to maximum during the light hours and decreasing from maximum to minimum during the dark.”

I don’t understand why there are two definitions of the _temperature function in the “Model Behaviour” section. Are these necessary, or is the first one just to say you need one and the second one to say what it actually should be..? I was confused by this.

I expected this code
env = ExperimentalEnv(sunrise=8, sunset=8)
to make a 0h photoperiod. Is sunset not the time of the sunset (rather than the duration of light)?

2024-12-08 14:59 UTC, csnazell commented
> What would the example in "creating an environment model" produce? Is it like the default but with an 8 hour photoperiod? How do you control the day duration instead?

The default model with no customisation has a zero hour photoperiod.  

`environment = Environment.ConstantModel(sunset=8)` will produce an 8 hour photoperiod running from 0 to 8.

The day duration can be adjusted with the constructor like everything else. I've updated the section to included it with the other parameters.

2024-12-08 15:23 UTC, csnazell commented
> In “#4 Create New Model - Model Data”, I would suggest adding a sentence to describe what your example will be doing to prepare the reader, before you show the code for it. e.g something like: “In this example we will set the temperature as increasing linearly from minimum to maximum during the light hours and decreasing from maximum to minimum during the dark.”
> 

Done.

2024-12-08 15:27 UTC, csnazell commented
> I don’t understand why there are two definitions of the _temperature function in the “Model Behaviour” section. Are these necessary, or is the first one just to say you need one and the second one to say what it actually should be..? I was confused by this.
> 

I tend to block out functionality & return to fill in details. I've merged the two stages into one.

2024-12-08 15:29 UTC, csnazell commented
> I expected this code env = ExperimentalEnv(sunrise=8, sunset=8) to make a 0h photoperiod. Is sunset not the time of the sunset (rather than the duration of light)?
>

That's a typo. I've corrected it to match the plot with sunrise at 0800 & sunset at 1600

2025-04-27 10:56 UTC, csnazell commented
Resolved conflict with main & merged

2025-04-27 10:56 UTC, closed without merging